### ISSUE TITLE
onSubmit option, conflict issue when content is filled using mouse

### ISSUE THREAD

**Issue by webVerts** [digitalfortress-tech/typeahead-standalone#30]
### What happened?

I haven't added anything new other than adding a onSubmit option to your existing code of accessing twitter data. onSubmit option for mouseclick and keystroke have different results.

### Affected version

Latest

### Reproduction URL

https://codepen.io/alanjam/pen/vYjNEGm?editors=1111

### How to reproduce?

Go to the link.
Type in your name and complete the suggestion using mouse click and click enter. 
An alert appears and click ok.
Open console log. You'll notice "SometihngSomething" messagge

Now go back and type your name again, this time complete autofilling using keystroke and click enter. 
Alert appears, click ok.
Open console log. You can find the stringified data from twitter there, which wasn't available when using mouse.

   

### Browsers

Brave

**Comment by webVerts** [comment]
also i get an following error
`DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/npm/typeahead-standalone.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by niketpathak** [comment]
Hello, thank you for reporting this bug. It has been fixed in [v4.11.0](https://github.com/digitalfortress-tech/typeahead-standalone/releases/tag/v4.11.0). 

Also to access the source maps, use a specific version in your script tag, for example => 
`<script src="https://cdn.jsdelivr.net/npm/typeahead-standalone@4.11.0/dist/typeahead-standalone.js">`
The will ensure that the source-maps load correctly (https://cdn.jsdelivr.net/npm/typeahead-standalone@4.11.0/dist/typeahead-standalone.js.map)

**Comment by webVerts** [comment]
Hey @niketpathak the issue still persists for me when `preventSubmit: false` . 

I might be wrong here, but according to my understanding, if I click on the username it should trigger the onSubmit function. With the keys it triggers as intended, but on using mouse click, it fills in the data in the form, but I don't receive data on my console log. I've updated the code [https://codepen.io/webVerts/pen/vYjNEGm](https://codepen.io/webVerts/pen/vYjNEGm)

**Comment by niketpathak** [comment]
Hey @webVerts ,

This is intended behavior. When you select a suggestion via your Keyboard(Arrow keys) and press the <kbd>Tab</kbd> key,
the behavior is similar to what would happen when you click on a suggestion. This is because you are only selecting a suggestion, but not submitting it, hence the `onSubmit` callback is not executed. 

The `onSubmit` callback is used to submit data when the input element is used outside of a form. It therefore gets executed only when you hit the <kbd>Enter</kbd> key. For example, when you select a suggestion by clicking on it, the input element will be filled with the necessary text. And then when you hit <kbd>Enter</kbd>, the `onSubmit` callback will be executed. 

I think what you are looking for is an `onSelect` callback which does not exist yet. If you could kindly elaborate on the use-case of why this callback would be useful/necessary, we will definitely include it in the next release. Thanks!

**Comment by speich** [comment]
I think you can handle pretty much all use cases with the config callback property `display`:

```javascript
display: (selectedItem, evt) => {
    if (evt && evt.type === 'click') {
      // submit form here
    }
    // if tab should not replace the input value with item.property
    return (evt && evt.key === 'Tab') ? evt.target.value : item.property;
}
```
